sudo: required
services:
 - docker

before_install:
 - docker build -t dockertraining/react-test -f ./client/Dockerfile.dev ./client/

script:
 - docker run -e CI=true dockertraining/react-test npm test

after_sucess:
 - docker build -t dockertraining/multi-client ./client
 - docker build -t dockertraining/multi-nginx ./nginx
 - docker build -t dockertraining/multi-server ./server
 - docker build -t dockertraining/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push dockertraining/multi-client
 - docker push dockertraining/multi-nginx
 - docker push dockertraining/multi-server
 - docker push dockertraining/multi-worker

